-- MySQL Script generated by MySQL Workbench
-- Ter 30 Mai 2017 02:20:31 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetoempresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoempresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoempresa` DEFAULT CHARACTER SET latin1 ;
USE `projetoempresa` ;

-- -----------------------------------------------------
-- Table `projetoempresa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoempresa`.`usuario` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `senha` VARCHAR(60) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nome` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo` ENUM('admin', 'cliente') COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8;


-- -----------------------------------------------------
-- Table `projetoempresa`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoempresa`.`empresa` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cnpj` VARCHAR(25) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `logradouro` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `numero_endereco` INT(11) NOT NULL,
  `cidade_endereco` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `bairro_endereco` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cep_endereco` VARCHAR(15) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nome_fantasia` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `razao_social` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `usuario_id` INT(10) UNSIGNED NOT NULL,
  `telefone` VARCHAR(25) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `empresa_email_unique` (`email` ASC),
  UNIQUE INDEX `empresa_nome_fantasia_unique` (`nome_fantasia` ASC),
  UNIQUE INDEX `empresa_razao_social_unique` (`razao_social` ASC),
  INDEX `empresa_usuario_id_foreign` (`usuario_id` ASC),
  CONSTRAINT `empresa_usuario_id_foreign`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projetoempresa`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `projetoempresa`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoempresa`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `projetoempresa`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoempresa`.`password_resets` (
  `email` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
